# Document:
# http://simiki.org/docs/configuration.html

url: https://yilingui.xyz/wiki/
title: Yilin's Wiki
keywords: 
description: 
author: Yilin Gui
root: /wiki/

deploy:
  - type: git
    remote: origin
    branch: gh-pages
